name: Build & Release on Tag

on:
  push:
    tags:
      - 'v*' # 例如 v1.0.0

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Build and Publish
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            npm run build:win -- --publish always
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            npm run build:mac -- --publish always
          else
            npm run build:linux -- --publish always
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
