name: Build & Release on Tag

on:
  push:
    tags:
      - 'v*' # 例如 v1.0.0

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      # 这里直接让 electron-builder 打包并上传到 GitHub Release
      - name: Build and Publish
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            npx electron-builder --win --x64 --publish always
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            npx electron-builder --mac --x64 --publish always
          else
            npx electron-builder --linux --x64 --publish always
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }} # 你的 PAT（或者直接用 GITHUB_TOKEN 也行）
